#!/usr/bin/sh
cpu=$(mpstat | awk '$13 ~ /[0-9.]+/ { printf("%.0f", 100 - $13) }')
echo $cpu%
echo $cpu%
if [ $cpu -ge 90 ]; then
  echo "#FF0000\n"
elif [ $cpu -ge 50 ]; then
  echo "#FFFC00\n"
else
  echo "#FFFFFF\n"
fi
