#!/usr/bin/sh
i3-msg "[title=\"^$1$\"] focus" | grep false && i3-msg exec "xterm -fn Hack-Regular -report-colors +sb -name vim-notes -T vim-notes -e 'vim -c \"Note current | set noshowcmd | set laststatus=0 | set noruler | set nornu | set nonu | set showtabline=0\"'"

