#!/usr/bin/env bash

# Copyright 2016 Patrick Haun
# Edited: Denis Kadyshev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

layout=`~/bin/xkblayout-state print "%s" | tr a-z A-Z`

if [ "$layout" == "US" ]; then
  echo $layout
  echo $layout
  echo "#8AFF92"
elif [ "$layout" == "RU" ]; then
  echo "<span weight='bold'>$layout</span>"
  echo "<span weight='bold'>$layout</span>"
  echo "#FF6666"
elif [ "$layout" == "IL" ]; then
  echo "<span weight='bold'>$layout</span>"
  echo "<span weight='bold'>$layout</span>"
  echo "#FF6666"
fi
case $BLOCK_BUTTON in
    1) ~/bin/next_keyboard_layout
esac
