#!/bin/bash
date >> ~/lock_dates.txt
scrot -q 1 /tmp/screen_locked.png
#i3lock -i /tmp/screen_locked.png

#convert /tmp/screen_locked.png -modulate 80 -blur 0x6 -brightness-contrast 5x5 /tmp/screen_locked2.png
#$HOME/bin/effects/camerablur -t defocus -a 7 /tmp/screen_locked.png /tmp/screen_locked2.png

$HOME/bin/effects/disperse -s 5 -d 2 -c 10 /tmp/screen_locked.png /tmp/screen_locked2.png
mv /tmp/screen_locked2.png /tmp/screen_locked.png
#$HOME/bin/effects/watercolor -s 0 -e 5 -m 33 -c 0 /tmp/screen_locked.png /tmp/screen_locked2.png
#mv /tmp/screen_locked2.png /tmp/screen_locked.png
convert /tmp/screen_locked.png -blur 0x2 /tmp/screen_locked2.png
mv /tmp/screen_locked2.png /tmp/screen_locked.png

pkill i3lock
i3lock -i /tmp/screen_locked.png
