return {
  { "folke/flash.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  { "lualine.nvim", enabled = false },
  { "hrsh7th/nvim-cmp", enabled = true },
  { "vim-dadbod-completion", enabled = false },
  { "saghen/blink.cmp", enabled = false },
}
